runtime: php55
api_version: 1

handlers:

# Accueil global
- url: /
  script: index.html

#Les ressources statiques
- url: /color
  static_dir: color
- url: /contactform
  static_dir: contactform
- url: /font-awesome
  static_dir: font-awesome
- url: /fonts
  static_dir: fonts
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /img
  static_dir: img
- url: /medias
  static_dir: medias

# Les pages
- url: /about
  script: about.html
- url: /contact
  script: contact.html
- url: /graphics
  script: graphics.html
- url: /experience
  script: experience.html